# This workflow will deploy the website to cPanel using FTP-Deploy-Action

name: Publish Website to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Specify the local directory to upload
          git-ftp-args: --insecure # Add any additional git-ftp arguments if needed
